server:
  port: 9001

spring:
  security:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/security
    username: root
    password: beijiake
  #    initialization-mode: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/test
    username: root
    password: beijiake

  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

url-patterns:
  secured: "/secured"
  public: "/pub"