server:
  port: 8081


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8
    username: root
    password: beijiake
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

url:
  api:
    prefix: "/api"

storage:
#  location: /users/mac/

authorization-server:
  token-url: http://localhost:9000/oauth/token
  client-id: clientid
  client-secret: clientsecret
